
services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile.dev
    environment:
      - MONGODB_URL=mongodb://admin:!ChangeMe!@mongodb:27017
      - MONGODB_DATABASE=reliquary
      - MONGO_APP_USERNAME=reliquary_user
      - MONGO_APP_PASSWORD=reliquary_password
    volumes:
      - .:/var/www
      - ./docker/app/php.ini:/usr/local/etc/php/conf.d/app.ini
    ports:
      - "8085:80"
      - "8443:443"
    depends_on:
      - database
      - mongodb
    restart: unless-stopped

###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-app}", "-U", "${POSTGRES_USER:-app}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

  mailpit:
    image: axllent/mailpit:latest
    ports:
      - "1025:1025"  # SMTP port
      - "8025:8025"  # Web UI port
    restart: unless-stopped

  mongodb:
    image: mongo:${MONGO_VERSION:-7.0}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:-!ChangeMe!}
      MONGO_INITDB_DATABASE: ${MONGO_DB:-reliquary}
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand('ping').ok", "--quiet"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - mongodb_data:/data/db:rw
      - ./docker/mongodb/init:/docker-entrypoint-initdb.d:ro
    restart: unless-stopped


volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
  mongodb_data:
